feat: refactor gormx
ahiho/gocandy pull request #7
Opened 2022-08-25 08:29 UTC by HuyLee15

2022-08-25 08:39 UTC, levanlongktmt commented on gormx/db.go
> +func (db *DB) Filter(filterReq string) *gorm.DB {
có cách nào return DB thay vì gorm.DB ko nhỉ

2022-08-25 08:51 UTC, HuyLee15 commented on gormx/db.go
> +func (db *DB) Filter(filterReq string) *gorm.DB {
> có cách nào return DB thay vì gorm.DB ko nhỉ

là sao a nhỉ, e ko hiểu lắm quả này

2022-08-25 08:55 UTC, levanlongktmt commented on gormx/db.go
> +}
```suggestion
type DB gorm.DB
```

2022-08-26 03:54 UTC, levanlongktmt requested changes

2022-08-26 03:54 UTC, levanlongktmt commented on gormx/pagination.go
> +func (db *DB) Filter(filterReq string, adaptor *filter.SQLAdaptor) *gorm.DB {
```suggestion
func (db *DB) Filter(filterReq string, adaptor *filter.SQLAdaptor) *DB {
```

2022-08-26 03:54 UTC, levanlongktmt commented on gormx/pagination.go
> +			return nil
wtf return nil ?

2022-08-26 03:54 UTC, levanlongktmt commented on gormx/pagination.go
> +func (db *DB) Filter(filterReq string, adaptor *filter.SQLAdaptor) *gorm.DB {
why `Filter` function inside `pagination.go` file ?

2022-08-26 10:35 UTC, levanlongktmt approved these changes

2022-08-26 10:35 UTC, merged